/********************************************************************
* /home/hovanes/GlueX/MCB/src/dictMCBOut.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/hovanes/GlueX/MCB/src/dictMCBOut.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictMCBOut();
extern void G__cpp_setup_inheritancedictMCBOut();
extern void G__cpp_setup_typetabledictMCBOut();
extern void G__cpp_setup_memvardictMCBOut();
extern void G__cpp_setup_globaldictMCBOut();
extern void G__cpp_setup_memfuncdictMCBOut();
extern void G__cpp_setup_funcdictMCBOut();
extern void G__set_cpp_environmentdictMCBOut();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/hovanes/GlueX/MCB/src/TUserMCBOut.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictMCBOutLN_TClass;
extern G__linked_taginfo G__dictMCBOutLN_TBuffer;
extern G__linked_taginfo G__dictMCBOutLN_TMemberInspector;
extern G__linked_taginfo G__dictMCBOutLN_TObject;
extern G__linked_taginfo G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictMCBOutLN_TUserMCBOut;

/* STUB derived class for protected member access */
