/********************************************************************
* /home/hovanes/GlueX/MCB/src/dictMCBInp.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/hovanes/GlueX/MCB/src/dictMCBInp.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictMCBInp();
extern void G__cpp_setup_inheritancedictMCBInp();
extern void G__cpp_setup_typetabledictMCBInp();
extern void G__cpp_setup_memvardictMCBInp();
extern void G__cpp_setup_globaldictMCBInp();
extern void G__cpp_setup_memfuncdictMCBInp();
extern void G__cpp_setup_funcdictMCBInp();
extern void G__set_cpp_environmentdictMCBInp();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/hovanes/GlueX/MCB/src/TUserMCBInp.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictMCBInpLN_TClass;
extern G__linked_taginfo G__dictMCBInpLN_TBuffer;
extern G__linked_taginfo G__dictMCBInpLN_TMemberInspector;
extern G__linked_taginfo G__dictMCBInpLN_TObject;
extern G__linked_taginfo G__dictMCBInpLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictMCBInpLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictMCBInpLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictMCBInpLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictMCBInpLN_TUserMCBInp;

/* STUB derived class for protected member access */
