//
// File generated by rootcint at Thu May 12 11:31:51 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIhomedIhovanesdIGlueXdIMCBdIsrcdIdictMCBOut
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dictMCBOut.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TUserMCBOut_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TUserMCBOut(void *p = 0);
   static void *newArray_TUserMCBOut(Long_t size, void *p);
   static void delete_TUserMCBOut(void *p);
   static void deleteArray_TUserMCBOut(void *p);
   static void destruct_TUserMCBOut(void *p);
   static void streamer_TUserMCBOut(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TUserMCBOut*)
   {
      ::TUserMCBOut *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TUserMCBOut >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TUserMCBOut", ::TUserMCBOut::Class_Version(), "/home/hovanes/GlueX/MCB/src/TUserMCBOut.h", 6,
                  typeid(::TUserMCBOut), DefineBehavior(ptr, ptr),
                  &::TUserMCBOut::Dictionary, isa_proxy, 0,
                  sizeof(::TUserMCBOut) );
      instance.SetNew(&new_TUserMCBOut);
      instance.SetNewArray(&newArray_TUserMCBOut);
      instance.SetDelete(&delete_TUserMCBOut);
      instance.SetDeleteArray(&deleteArray_TUserMCBOut);
      instance.SetDestructor(&destruct_TUserMCBOut);
      instance.SetStreamerFunc(&streamer_TUserMCBOut);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TUserMCBOut*)
   {
      return GenerateInitInstanceLocal((::TUserMCBOut*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TUserMCBOut*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr TUserMCBOut::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TUserMCBOut::Class_Name()
{
   return "TUserMCBOut";
}

//______________________________________________________________________________
const char *TUserMCBOut::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TUserMCBOut*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TUserMCBOut::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TUserMCBOut*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TUserMCBOut::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TUserMCBOut*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TUserMCBOut::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TUserMCBOut*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TUserMCBOut::Streamer(TBuffer &R__b)
{
   // Stream an object of class TUserMCBOut.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.ReadStaticArray((char*)bremsprocs);
      R__b >> MaxH;
      R__b >> MaxKL;
      R__b >> IntensityMin;
      R__b >> IntensityMax;
      R__b >> IntensityTot;
      R__b >> NormVolume;
      R__b >> no_Electrons;
      R__b >> no_Photons;
      R__b >> no_OutOfBounds;
      R__b >> no_CollPhotons;
      R__b.ReadStaticArray((int*)RandomVectors);
      R__b.CheckByteCount(R__s, R__c, TUserMCBOut::IsA());
   } else {
      R__c = R__b.WriteVersion(TUserMCBOut::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.WriteArray(bremsprocs, 5);
      R__b << MaxH;
      R__b << MaxKL;
      R__b << IntensityMin;
      R__b << IntensityMax;
      R__b << IntensityTot;
      R__b << NormVolume;
      R__b << no_Electrons;
      R__b << no_Photons;
      R__b << no_OutOfBounds;
      R__b << no_CollPhotons;
      R__b.WriteArray(RandomVectors, 25);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TUserMCBOut::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TUserMCBOut.
      TClass *R__cl = ::TUserMCBOut::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bremsprocs[5]", bremsprocs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxH", &MaxH);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MaxKL", &MaxKL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IntensityMin", &IntensityMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IntensityMax", &IntensityMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IntensityTot", &IntensityTot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NormVolume", &NormVolume);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "no_Electrons", &no_Electrons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "no_Photons", &no_Photons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "no_OutOfBounds", &no_OutOfBounds);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "no_CollPhotons", &no_CollPhotons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "RandomVectors[25]", RandomVectors);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TUserMCBOut(void *p) {
      return  p ? new(p) ::TUserMCBOut : new ::TUserMCBOut;
   }
   static void *newArray_TUserMCBOut(Long_t nElements, void *p) {
      return p ? new(p) ::TUserMCBOut[nElements] : new ::TUserMCBOut[nElements];
   }
   // Wrapper around operator delete
   static void delete_TUserMCBOut(void *p) {
      delete ((::TUserMCBOut*)p);
   }
   static void deleteArray_TUserMCBOut(void *p) {
      delete [] ((::TUserMCBOut*)p);
   }
   static void destruct_TUserMCBOut(void *p) {
      typedef ::TUserMCBOut current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TUserMCBOut(TBuffer &buf, void *obj) {
      ((::TUserMCBOut*)obj)->::TUserMCBOut::Streamer(buf);
   }
} // end of namespace ROOT for class ::TUserMCBOut

/********************************************************
* /home/hovanes/GlueX/MCB/src/dictMCBOut.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledictMCBOut();

extern "C" void G__set_cpp_environmentdictMCBOut() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/hovanes/GlueX/MCB/src/TUserMCBOut.h");
  G__cpp_reset_tagtabledictMCBOut();
}
#include <new>
extern "C" int G__cpp_dllrevdictMCBOut() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TUserMCBOut */
static int G__dictMCBOut_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TUserMCBOut* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TUserMCBOut[n];
     } else {
       p = new((void*) gvp) TUserMCBOut[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TUserMCBOut;
     } else {
       p = new((void*) gvp) TUserMCBOut;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TUserMCBOut::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUserMCBOut::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TUserMCBOut::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TUserMCBOut::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TUserMCBOut*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUserMCBOut::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TUserMCBOut::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TUserMCBOut::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictMCBOut_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TUserMCBOut::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictMCBOut_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TUserMCBOut* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TUserMCBOut(*(TUserMCBOut*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TUserMCBOut G__TTUserMCBOut;
static int G__dictMCBOut_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TUserMCBOut*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TUserMCBOut*) (soff+(sizeof(TUserMCBOut)*i)))->~G__TTUserMCBOut();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TUserMCBOut*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TUserMCBOut*) (soff))->~G__TTUserMCBOut();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictMCBOut_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TUserMCBOut* dest = (TUserMCBOut*) G__getstructoffset();
   *dest = *(TUserMCBOut*) libp->para[0].ref;
   const TUserMCBOut& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TUserMCBOut */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdictMCBOut {
 public:
  G__Sizep2memfuncdictMCBOut(): p(&G__Sizep2memfuncdictMCBOut::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdictMCBOut::*p)();
};

size_t G__get_sizep2memfuncdictMCBOut()
{
  G__Sizep2memfuncdictMCBOut a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedictMCBOut() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut))) {
     TUserMCBOut *G__Lderived;
     G__Lderived=(TUserMCBOut*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut),G__get_linked_tagnum(&G__dictMCBOutLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledictMCBOut() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TUserMCBOut */
static void G__setup_memvarTUserMCBOut(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut));
   { TUserMCBOut *p; p=(TUserMCBOut*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->bremsprocs)-(long)(p)),99,0,0,-1,-1,-1,1,"bremsprocs[5]=",0,"amo,inC,inR,ihb,sum,dif");
   G__memvar_setup((void*)((long)(&p->MaxH)-(long)(p)),105,0,0,-1,-1,-1,1,"MaxH=",0,"max lattice index for H");
   G__memvar_setup((void*)((long)(&p->MaxKL)-(long)(p)),105,0,0,-1,-1,-1,1,"MaxKL=",0,"max lattice index for K,L");
   G__memvar_setup((void*)((long)(&p->IntensityMin)-(long)(p)),100,0,0,-1,-1,-1,1,"IntensityMin=",0,"min intensity");
   G__memvar_setup((void*)((long)(&p->IntensityMax)-(long)(p)),100,0,0,-1,-1,-1,1,"IntensityMax=",0,"max intensity");
   G__memvar_setup((void*)((long)(&p->IntensityTot)-(long)(p)),100,0,0,-1,-1,-1,1,"IntensityTot=",0,"max value set by input");
   G__memvar_setup((void*)((long)(&p->NormVolume)-(long)(p)),100,0,0,-1,-1,-1,1,"NormVolume=",0,"random volume for normalization");
   G__memvar_setup((void*)((long)(&p->no_Electrons)-(long)(p)),100,0,0,-1,-1,-1,1,"no_Electrons=",0,"no of electrons used in run");
   G__memvar_setup((void*)((long)(&p->no_Photons)-(long)(p)),100,0,0,-1,-1,-1,1,"no_Photons=",0,"no of photons, preset");
   G__memvar_setup((void*)((long)(&p->no_OutOfBounds)-(long)(p)),100,0,0,-1,-1,-1,1,"no_OutOfBounds=",0,"no of photons out of range of code");
   G__memvar_setup((void*)((long)(&p->no_CollPhotons)-(long)(p)),100,0,0,-1,-1,-1,1,"no_CollPhotons=",0,"no of photons within collimator");
   G__memvar_setup((void*)((long)(&p->RandomVectors)-(long)(p)),105,0,0,-1,-1,-1,1,"RandomVectors[25]=",0,"25 random vectors");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictMCBOutLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardictMCBOut() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTUserMCBOut(void) {
   /* TUserMCBOut */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut));
   G__memfunc_setup("TUserMCBOut",1021,G__dictMCBOut_168_0_1, 105, G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dictMCBOut_168_0_2, 85, G__get_linked_tagnum(&G__dictMCBOutLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TUserMCBOut::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictMCBOut_168_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUserMCBOut::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictMCBOut_168_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TUserMCBOut::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictMCBOut_168_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TUserMCBOut::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictMCBOutLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictMCBOut_168_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictMCBOut_168_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUserMCBOut::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictMCBOut_168_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TUserMCBOut::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictMCBOut_168_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TUserMCBOut::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictMCBOut_168_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TUserMCBOut::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TUserMCBOut", 1021, G__dictMCBOut_168_0_14, (int) ('i'), G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut), -1, 0, 1, 1, 1, 0, "u 'TUserMCBOut' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TUserMCBOut", 1147, G__dictMCBOut_168_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictMCBOut_168_0_16, (int) ('u'), G__get_linked_tagnum(&G__dictMCBOutLN_TUserMCBOut), -1, 1, 1, 1, 1, 0, "u 'TUserMCBOut' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdictMCBOut() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldictMCBOut() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdictMCBOut() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictMCBOutLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictMCBOutLN_TUserMCBOut = { "TUserMCBOut" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledictMCBOut() {
  G__dictMCBOutLN_TClass.tagnum = -1 ;
  G__dictMCBOutLN_TBuffer.tagnum = -1 ;
  G__dictMCBOutLN_TMemberInspector.tagnum = -1 ;
  G__dictMCBOutLN_TObject.tagnum = -1 ;
  G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictMCBOutLN_TUserMCBOut.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledictMCBOut() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictMCBOutLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictMCBOutLN_TUserMCBOut),sizeof(TUserMCBOut),-1,29952,(char*)NULL,G__setup_memvarTUserMCBOut,G__setup_memfuncTUserMCBOut);
}
extern "C" void G__cpp_setupdictMCBOut(void) {
  G__check_setup_version(30051515,"G__cpp_setupdictMCBOut()");
  G__set_cpp_environmentdictMCBOut();
  G__cpp_setup_tagtabledictMCBOut();

  G__cpp_setup_inheritancedictMCBOut();

  G__cpp_setup_typetabledictMCBOut();

  G__cpp_setup_memvardictMCBOut();

  G__cpp_setup_memfuncdictMCBOut();
  G__cpp_setup_globaldictMCBOut();
  G__cpp_setup_funcdictMCBOut();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdictMCBOut();
  return;
}
class G__cpp_setup_initdictMCBOut {
  public:
    G__cpp_setup_initdictMCBOut() { G__add_setup_func("dictMCBOut",(G__incsetup)(&G__cpp_setupdictMCBOut)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdictMCBOut() { G__remove_setup_func("dictMCBOut"); }
};
G__cpp_setup_initdictMCBOut G__cpp_setup_initializerdictMCBOut;

